root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/recommended'
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  quotes: [error, single]
  jsx-quotes: [error, prefer-single]
  comma-dangle: [error, always-multiline]
