trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: true
plugins:
  - "@trivago/prettier-plugin-sort-imports"
importOrder:
  - "react"
  - "<THIRD_PARTY_MODULES>"
  - "^@mui/(.*)$"
  - "app/(.*)$"
importOrderSeparation: true
importOrderSortSpecifiers: true
