trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: true
jsxSingleQuote: true
plugins:
  - "@trivago/prettier-plugin-sort-imports"
importOrder:
  - "react"
  - "<THIRD_PARTY_MODULES>"
  - "^@prisma/(.*)$"
  - "^@mui/(.*)$"
  - "^@/(.*)$"
importOrderSeparation: true
importOrderSortSpecifiers: true
